data-eden/data-eden

packages/athena/package.json, packages/cache/package.json, packages/network/package.json
Setting these `exports` up early, helps prevent folks from importing deeply.
=> Only allow importing from the entry point of each package

.github/workflows/ci.yml
use maintenance, lts and latest versions of node.
node@12 fails current test cases and is not in maintenance.
=> chore: use maintenance, lts and latest versions of node

packages/network/__tests__/fetch-test.ts, packages/network/src/fetch.ts
=> chore: increase test coverage for @data-eden/network

.eslintrc.cjs, package-lock.json, package.json
This follows the official guidance of the Prettier team ([from here](https://prettier.io/docs/en/integrating-with-linters.html#notes)):
> The downsides of those plugins are:
>
> 1. You end up with a lot of red squiggly lines in your editor, which gets annoying. Prettier is supposed to make you forget about formatting – and not be in your face about it!
> 2. They are slower than running Prettier directly.
> 3. They’re yet one layer of indirection where things may break.
---
**tldr;** in practice, folks are unlikely to notice this change (other than that they won't have so many "annoying red squiggles").
After this change:
* `eslint` will not flag prettier errors
* Most editors will continue to use prettier on save (this is a very common setup for folks using VSCode / NeoVim / etc)
* CI …
=> Remove `prettier` integration from eslint setup.

CHANGELOG.md, package.json
The published output does not contain the dist directory
I utilized the release-it hooks before the npm hooks are not being triggered via release-it
=> bug: adds prepublish to make sure published packages have dist and d.ts file

.prettierignore
The `CHANGELOG.md` is auto-generated (by `lerna-changelog`), and at the moment it emits content that doesn't pass `prettier --check`.
This change instructs `prettier` to ignore `CHANGELOG.md`, so that releasing doesn't cause subsequent CI failures.
=> Add `CHANGELOG.md` to `.prettierignore`

packages/network/src/index.ts
I am working on an external middleware and can't import the types necessary.
=> feat: export types from fetch to utilize in external middlewares

packages/network/src/index.ts, tsconfig-base.json
Without these changes, the package is failed to be seen as an esm package natively.
=> chore: makes changes to be able to consume as an esm package

packages/network/package.json
https://webpack.js.org/guides/package-exports/#common-patterns expects a default when it doesn't understand the sub fields for a given expression. When bringing this into a project it failed unless this was added.
=> feat: have a default export to handle webpack use case

packages/athena/package.json, packages/cache/package.json, packages/network/package.json
When TypeScript consumers are using `moduleResolution: 'node'` (which is the only real value that folks using older TypeScript or Node versions could have used) the `exports` property is never used / accessed. Adding `main`/`typings` enables consumers using `moduleResolution: 'node'` to work without requiring a TypeScript bump, or themselves to migrate to `node16`.
=> Add `main` and `typings` to packages

packages/network/__tests__/fetch-test.ts
This adds a test showing that earlier middlewares can wrap later middlewares _including_ any response munging that is done by the later middlewares)
=> Add test for middleware ordering (including results)

package-lock.json, packages/network/__tests__/fetch-test.ts, packages/network/__tests__/utils.ts, packages/network/package.json
`msw` does not currently support Node 18's native fetch. This adds a mega simple native http server that we can use instead.
Additionally, this tweaks the tests to assert _only_ on the specific headers that we care about.
Unblocks https://github.com/data-eden/data-eden/pull/45
=> Replace `msw` with `http` server

internal-packages/shared-test-utilities/src/server.ts
We don't _need_ to wait for the server to be closed in order to continue execution (many examples in Node's own documentation run `server.close(); server.listen(host, port)` back to back).
This removes a ~ 4 second delay in `@data-eden/network`'s test suite (during `afterAll` where we call `await server.close()`).
=> Improve test performance: Don't wait on `server.close()`

packages/cache/package.json
For published assets, we **must** use `dist/` in our `exports`.
We ultimately want to use `src/` locally and change this to `dist/` upon publish, but at the moment things are fundamentally broken for WebPack consumers so this is a "quick fix" for the published consumer.
A follow-on PR should fix all of our workspaces to use `src/` checked in, and update to `dist/` locations for `npm publish`.
=> Use `dist/` for exports in @data-eden/cache

package.json
Rolls back a change made in 668282adaef6383777f584e4f49ca5e140286014 (and pushed directly to `main`).
/cc @gabrielcsapo
=> Ensure changelog can be edited before publishing.

package.json
This helps ensure that `package-lock.json` is kept in sync (with the current setup, `@release-it-plugins/workspaces` **does _not_** ensure that `package-lock.json` is up to date).
References https://github.com/release-it-plugins/workspaces/issues/85
=> Run `npm install` after the versions are bumped

packages/network/__tests__/fetch-test.ts, packages/network/src/fetch.ts
Currently, it is not possible to mock `fetch` **after** `buildFetch` is invoked. This might _seem_ fine, but ultimately it is not:
- Generally speaking we expect `buildFetch` to be done **very** early in the application's evaluation. Specifically, this will be **_well_** before any individual tests are kicked off / ran.
- Tools like `Pretender` / `MirageJS` / `msw` need to be able to override `globalThis.fetch` lazily. Most of the time this is done within a specific test context (or after the tests have kicked off, in a `beforeEach`/`beforeAll` kinda of situation). Notably, these tests will almost certainly be directly `import { fetch } from 'app-name/network'` or something (which **guarantees** that the `buildFetch` will have been called already).
This commit ensures that …
=> Ensure that `fetch` is only accessed lazily (allow mocking)

.eslintrc.cjs, dev/simple-fetch-script.js, internal-packages/shared-test-utilities/package.json
Running `node --inspect-brk dev/simple-fetch-script.js` allows you to more easily step through `@data-eden/network`'s implementation.
=> Add script to easily step through `buildFetch` usage.

packages/network/__tests__/fetch-test.ts, packages/network/src/fetch.ts, packages/network/src/index.ts
In some circumstances a middleware may need access to some metadata in order to perform its purpose. For example, a middleware that tracks requests/response (e.g. for tracking API failure rates) would want to ensure that it tracks those requests back to the original `buildFetch` (remember, there can _and will_ likely be many `buildFetch` calls within a large and complicated application) that ultimately triggered the requests to be fired.
In the future, this metadata will likely be expanded to include other information (e.g. `$debug` info). Those use cases can augment the infrastructure introduced here.
=> Expose metadata to middlewares

packages/cache/README.md, packages/cache/__tests__/index-test.ts, packages/cache/src/cache.ts
The original intention was for `rollback` to function similarly as in SQL -- i.e. to render the transaction invalid.  But it's less important if we structure `tx.commit` as a diff (see #81).
=> Remove rollback

packages/network/__tests__/fetch-test.ts
There is no requirement that a given middleware **must** call `next`, it is perfectly fine to directly return a response.
A common scenario for this might be to handle caching for a given request.
Closes #87
=> Add test showing how to return a cached response

package.json
Uses the `build` script, so any flag chagnes are shared
automatically.
Locally, without the `--build` flag I do not always get `dist/` created
in all of the workspaces.
=> Ensure top level `build:watch` runs `tsc --build --watch`

packages/network/src/fetch.ts, packages/network/src/index.ts, packages/network/src/settled-tracking-middleware.ts
We don't want to export a public custom `Fetch` type.  The mental model users should have is that `buildFetch()` returns a `typeof fetch` -- i.e. a fully fetch-compatible function.
The docs show `type Fetch = typeof fetch` as an example of something users might do to make their own code more readable, but it is not something that should be part of `@data-eden/network`'s public API.
=> chore: remove Fetch type export

.eslintrc.cjs, internal-packages/react-graphql-test-app/src/@types/graphql.d.ts, internal-packages/shared-test-utilities/__tests__/server.test.ts, packages/cache/__tests__/index-test.ts, packages/network/__tests__/fetch-test.ts, packages/network/__tests__/settled-tracking-middleware-test.ts
Turn on [@typescript-eslint/consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports/) and run `lint:fix`
=> enforce consistent type imports

packages/codegen/__tests__/__snapshots__/codegen.test.ts.snap, packages/codegen/__tests__/codegen.test.ts, packages/codegen/__tests__/utils/project.ts, packages/codegen/src/codegen.ts, packages/codegen/src/types.ts
1. gql tags with re-exported fragments (❌ skipped, does not pass)
2. gql tags with fragments used locally + exported (✅ passes)
=> tests: add tests

packages/codegen/__tests__/codegen.test.ts, packages/codegen/src/bin.ts, packages/codegen/src/codegen.ts, packages/codegen/src/types.ts
This lets us skip schema generation in cases where the schema types are
already generated.
[fix #120]
=> feat: add --disable-schema-types-generation

packages/athena/vitest.config.ts, packages/cache/vitest.config.ts, packages/codegen/__tests__/babel.test.ts, packages/codegen/__tests__/codegen.test.ts, packages/codegen/vitest.config.ts, packages/network/__tests__/settled-tracking-middleware-test.ts
Talking with @hjdivad we couldn't get src file changes on change.
This was a result of the import in the test being an alias and vite not wanting to watch the path.
=> chore: make it possible to have tests update on src file changes

internal-packages/shared-test-utilities/src/index.ts, packages/network/__tests__/fetch-test.ts, packages/network/__tests__/settled-tracking-middleware-test.ts, packages/network/src/dev.d.ts, packages/network/src/fetch.ts, packages/network/src/settled-tracking-middleware.ts
When using the `fetch` that is returned by `buildFetch` it is often useful to debug individual middlewares or to check if there are any pending requests. The current implementation makes that quite difficult.
This PR adds a new `debug` option to `buildFetch`. As long as `{ debug: false }` isn't explicitly passed, the returned `fetch` function will have a `$debug` property with the following interface:
```typescript
type FetchWithDebug = typeof fetch & {
$debug: {
creationStack: string;
middlewares: Middleware[];
};
};
```
Additionally, if you are also using the `SettledTrackingMiddleware` you will have even more information available (though only after the first `fetch(...)` invocation).
```typescript
type FetchWithDebug = typeof fetch & {
$debug: {
creationStack: string;
middlewares: …
```
=> Add a `$debug` property to the `buildFetch` result.

packages/cache/src/cache.ts
Add `FinalizationRegistry` to weakCahe to remove the strongly held keys after the value is garbage-collected.
completes task: https://github.com/data-eden/data-eden/issues/105
=> [cache] Implement FinalizationRegistry to remove keys

packages/cache/__tests__/index-test.ts, packages/cache/src/cache-revision.ts, packages/cache/src/cache-transaction.ts, packages/cache/src/cache.ts, packages/cache/src/live-transaction.ts, packages/cache/types/api.d.ts
- The cache impl was in one large file. This PR splits it into separate files per class for easier readability
- Fixed minor logical patterns w.r.t CommittingCache and Revisions impl.
=> [cache] split cache classes into separate files

packages/athena/__tests__/client.test.ts, packages/athena/src/signal-cache.ts
Follow-on to https://github.com/data-eden/data-eden/pull/141 that removes the duplicated `visited` check logic
=> [athena] remove duplicate visited check in resolve

internal-packages/react-graphql-test-app/src/components/DisplayPerson.tsx, internal-packages/react-graphql-test-app/src/default-data/display-person-data.ts, packages/react/src/setup-dependency-tracking.ts, packages/react/src/use-mutation.ts, packages/react/src/use-query.ts
This PR adds two new features to `useQuery`:
1. A `lazy` option that will stop `useQuery` from firing on component render (i.e. the user decides when to actually fire the query).
2. An `initialData` option that will populate the cache with whatever data is provided before firing the query (assuming the hook isn't in lazy mode).
These features serve two main purposes: cases where you've already got data in your app due to server rendering, and cases where you just need more control of when you'd like to fire a query.
=> feature: add lazy query option

.eslintignore, internal-packages/react-graphql-test-app/src/graphql/schema.graphql, package-lock.json, packages/mocker/__tests__/mocker.test.ts, packages/mocker/package.json, packages/mocker/src/index.ts, packages/mocker/tsconfig.build.json, packages/mocker/tsconfig.json, packages/mocker/vite.config.ts, tsconfig.json
Right now it requires passing a manually parsed query, the next pass on this will be hooking this up with codegen and specifically having codegen produce a rollup plugin to provide a zero configuration option for codegen.
=> feat: create mocker with basic support for fragments, queries and mutations

package-lock.json, packages/codegen/src/rollup-plugin.ts, packages/mocker/__tests__/mocker.test.ts, packages/mocker/package.json, packages/mocker/src/index.ts, packages/mocker/vitest.config.ts
properly returns the value of the typeddocumentnode as data to ensure type checking works correctly
> This also fixes the rollup plugin to avoid reading from disk and getting the raw value and instead just parsing the code given to the plugin which helps avoid typescript problems that we solved with rollup plugin babel
=> feat: enable mocker to properly return typed data

internal-packages/react-graphql-test-app/src/routes/FetchMore.tsx, package-lock.json, packages/react/__tests__/utils.test.ts, packages/react/package.json, packages/react/src/use-query.ts, packages/react/src/utils.ts, packages/react/vitest.config.ts
when initial data comes back as undefined, merging was not accommodating for that.
=> bug: fix findMore when data at certain levels is undefined when merging

internal-packages/react-graphql-test-app/src/routes/FetchMore.tsx, packages/react/src/use-query.ts
made a new experience to show this functionality. When calling refetch with initial data hook wasn't setting up dependencies correctly resulting in data not being updated.
=> bug: ensure that we retrigger dependency setup when calling refetch

packages/cache/src/cache.ts, packages/cache/types/api.d.ts
same version of typescript but exposes type issue
=> bug: integration into downstreams exposes type issue in cache

.github/workflows/ci.yml, internal-packages/react-graphql-test-app/vite.config.ts, package-lock.json, packages/athena/.gitignore, packages/athena/__tests__/client.test.ts, packages/athena/package.json, packages/athena/src/client.ts, packages/athena/src/signal-cache.ts, packages/athena/src/types.ts, packages/athena/vitest.config.ts
- allow getCacheKey to return undefined value
- allow entities with no cache key handle unmanaged entities
- utilizes @data-eden/mocker in tests
- writes new tests for client query (we should write more)
=> feat: support non-managed entities

packages/athena/__tests__/client.test.ts, packages/athena/__tests__/signal-cache.test.ts, packages/athena/src/client.ts, packages/athena/src/signal-cache.ts, packages/athena/src/types.ts, packages/athena/src/utils.ts
- creates a synthetic key hook for unmanaged entities via getCacheKey (these are entities that you know will change data but don't want to key off of the data itself but potentially on the path)
- adds tests
- removes code where we had objects that were not signals nested
- fixes a bug where parentArray was not terminating so nested keys would be keyed in parentArray
=> feat: handle unmanaged objects with synthetic keys

packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap, packages/mocker/__tests__/mocker.test.ts, packages/mocker/src/index.ts, packages/mocker/vite.config.ts
previously we did not support mocking top level fragment types that were union values
```graphql
fragment owner on Owner {
... on Person {
__typename
id
name
car {
__typename
id
make
}
}
... on Company {
__typename
id
name
}
}
```
with this change we can.
This also fixes an issue where we were not properly matching types and always projecting all types for all possible union types.
=> feat: support union fragments mocking top level

packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap, packages/mocker/__tests__/mocker.test.ts, packages/mocker/src/index.ts
All values are optional as required fields will be mocked out. The screenshots below show autocomplete with typescript. As a result of this I fixed all the type errors that were in tests.
=> feat: thread types through to get autcomplete for mockData

internal-packages/react-graphql-test-app/package.json, internal-packages/react-graphql-test-app/vite.config.ts, package-lock.json, package.json, packages/athena/__tests__/client.test.ts, packages/athena/src/client.ts, packages/athena/src/signal-cache.ts, packages/athena/src/types.ts, packages/athena/src/utils.ts, packages/codegen/__tests__/bin.test.ts, packages/codegen/__tests__/codegen.test.ts, packages/codegen/src/codegen.ts, packages/codegen/src/generate-document-files.ts, packages/codegen/src/gql/output-operations.ts, packages/codegen/src/index.ts, packages/codegen/src/types.ts, packages/ember/package.json, packages/react/src/use-query.ts, tsconfig.json
- updates Athena to handle token logic based on available fields to distinguish between persisted or raw query execution
- adds more information to the query-identifiers.json file to assist in figuring out where queries originate from
- breaking: no longer supports raw strings as operations, must be a operation token
> Test this in internal-packages/react-graphql-test-app (this command enables process.env.NODE_ENV=production)
```
npm run dev:prod
```
> Test this in internal-packages/react-graphql-test-app
```
npm run dev
```
=> feat: enable persisted or raw query execution

packages/mocker/src/index.ts
[Faker float guide](https://fakerjs.dev/api/number.html#float)
`[@faker-js/faker]: faker.datatype.number() is deprecated since v8.0 and will be removed in v9.0. Please use faker.number.int() instead.`
=> Fix faker float deprecation warning

packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap, packages/mocker/__tests__/mocker.test.ts, packages/mocker/src/index.ts
properly checks for the field node name taking into account if it is an alias.
=> feat: handle field alias mocking

packages/athena/__tests__/client.test.ts, packages/athena/vitest.config.ts, packages/cache/__tests__/index-test.ts, packages/cache/src/cache.ts, packages/cache/src/live-transaction.ts
updates the transaction merging behavior to look for prior entities in the transaction itself as well as the cache so that we don’t accidentally overwrite multiple instances of the same entry in the same transaction
=> fix transaction merging

packages/codegen/__tests__/__snapshots__/codegen.test.ts.snap, packages/codegen/__tests__/codegen.test.ts, packages/codegen/src/codegen.ts, packages/codegen/src/generate-document-files.ts, packages/codegen/src/gql/extract-definitions.ts, packages/codegen/src/gql/extractor.ts, packages/codegen/src/types.ts, packages/codegen/src/utils.ts
For special casing injection you can now do 
```js
await athenaCodegen({
schemaPath: 'schema.graphql',
documents: [`${project.baseDir}/**/*.tsx`],
baseDir: project.baseDir,
extension: '.graphql.ts',
disableSchemaTypesGeneration: false,
fieldInjection: {
User: {
name: 'role',
alias: 'userRole',
},
},
production: false,
});
```
This will most likely supersede the need for primaryKey injection as you can use this instead, will deprecate that in a later PR.
=> feat: enable field injection for special cases in codegen
