- .eslintrc.cjs
- package-lock.json
- package.json
- packages/athena/__tests__/index-test.ts
- packages/cache/__tests__/index-test.ts
- packages/network/__tests__/fetch-test.ts
- packages/network/src/fetch.ts
- tsconfig.eslint.json
- Add typescript <-> eslint integration
- Fixup @typescript-eslint failures
> Add eslint <-> TypeScript integration

- CONTRIBUTING.md
- README.md
GitHub does a good job showing this files contents to new contributors when they are making a PR.
> Setup basic CONTRIBUTING.md.

- package-lock.json
- package.json
- packages/athena/package.json
- packages/cache/package.json
- packages/network/package.json
- Add `npm run lint:package-json`
- Add `npm run lint:package-json:fix`
- Setup `lint-staged` for `package.json` files
- Run `npm run lint:fix`
> Add simple package.json linting setup

- packages/network/README.md
- packages/network/__tests__/fetch-test.ts
fixes #27 
* updates readme to have consistent language
* adds test to showcase analytics type middleware where data can be introspected from a given response
> chore: updates readme text and adds tests to showcase example in readme

- package-lock.json
- packages/network/__tests__/fetch-test.ts
- packages/network/package.json
Allows us to remove `TODO` RE: deep imports
> Update msw to latest

- README.md
- packages/athena/README.md
This pull request updates the README files for the Data-Eden library documentation. The changes include updating the introduction to provide a better overview of the library.
> Doc updates

- .github/workflows/ci.yml
> Drop support for Node 14

- packages/cache/src/cache.ts
- packages/cache/src/index.ts
- packages/cache/types/api.d.ts
- packages/ember/package.json
fixes https://github.com/data-eden/data-eden/issues/73
> Make cache.commitTransaction private

- packages/cache/__tests__/index-test.ts
- packages/cache/src/cache.ts
- packages/cache/src/index.ts
- packages/cache/types/api.d.ts
1. further refactor https://github.com/data-eden/data-eden/issues/75 & https://github.com/data-eden/data-eden/issues/80
2. fix https://github.com/data-eden/data-eden/issues/79
3. fix https://github.com/data-eden/data-eden/issues/74
4. fix https://github.com/data-eden/data-eden/issues/78
5. fix https://github.com/data-eden/data-eden/issues/76
> refactor delete, merge and tx iterators

- internal-packages/react-graphql-test-app/src/components/AddPet.tsx
- internal-packages/react-graphql-test-app/src/components/DisplayPerson.tsx
- internal-packages/react-graphql-test-app/src/components/DisplayPet.tsx
- internal-packages/react-graphql-test-app/src/components/UpdateCar.tsx
- internal-packages/react-graphql-test-app/src/components/UpdatePerson.tsx
- internal-packages/react-graphql-test-app/src/components/UpdatePet.tsx
- internal-packages/react-graphql-test-app/src/routes/MutationResult.tsx
- internal-packages/react-graphql-test-app/src/routes/QueryEffect.tsx
- internal-packages/react-graphql-test-app/src/routes/Unrelated.tsx
- package-lock.json
- packages/athena/src/index.ts
- packages/codegen/__tests__/babel.test.ts
- packages/codegen/__tests__/utils/project.ts
- packages/codegen/package.json
- packages/codegen/src/gql.ts
- packages/codegen/src/index.ts
- packages/react/src/index.ts
> [codegen] export gql from codegen not @data-eden/react

- packages/codegen/src/generate-document-files.ts
Report the file name that failed (e.g. parsing) when processing
documents.
> chore: Improve errors

- packages/cache/README.md
- packages/cache/__tests__/index-test.ts
- packages/cache/src/cache.ts
- packages/cache/src/index.ts
- packages/cache/types/api.d.ts
Fixes https://github.com/data-eden/data-eden/issues/81
https://github.com/data-eden/data-eden/issues/79 - provide a mergeStrategy override
>  [cache] restructure tx.commit with cache locking

- package-lock.json
- packages/codegen/README.md
- packages/codegen/__tests__/babel.test.ts
- packages/codegen/__tests__/codegen.test.ts
- packages/codegen/package.json
- packages/codegen/src/babel-plugin.ts
- packages/codegen/src/gql.ts
- packages/codegen/src/gql/foreign-ref-resolver.ts
- packages/codegen/src/gql/output-operations.ts
- documents foot guns in current codegen reqiurements
- updates createImportName to avoid collisions with types and local variables
- removes type-fest to avoid portable typing issues
- provides better error logging for foreign resolutions that could not be resolved (this is different than foreignDefinition that were null)
> chore: multiple fixes to integrate into next application

- packages/codegen/__tests__/babel.test.ts
- packages/codegen/src/babel-plugin.ts
> [codegen] remove @data-eden/codegen/gql when running babel transform

- packages/codegen/__tests__/babel.test.ts
- packages/codegen/src/babel-plugin.ts
> [codegen] fragment replacement results in warnings in build

- packages/codegen/__tests__/bin.test.ts
- packages/codegen/__tests__/codegen.test.ts
- packages/codegen/__tests__/utils.test.ts
- packages/codegen/src/codegen.ts
- packages/codegen/src/generate-document-files.ts
- packages/codegen/src/gql/extract-definitions.ts
- packages/codegen/src/gql/extractor.ts
- packages/codegen/src/types.ts
- packages/codegen/src/utils.ts
> [codegen] support primary key aliasing

- packages/network/src/settled-tracking-middleware.ts
In some bundling contexts (e.g. webpack as used by ember-auto-import) you might end up with multiple copies of this module in the final bundle. In that case we need to ensure that we have a single global tracking map. We do this by using a symbol that is the same across all copies, and then using that symbol to store the map on the global object.
This ensures that at any given time (regardless of how many copies of this module exist) we can always get the same map (and therefore our API's work properly).
> Ensure that TrackingInfoPerFetch is always shared across all versions.

- packages/mocker/README.md
> chore: adds mocker readme

- internal-packages/website/docusaurus.config.js
- internal-packages/website/package.json
- package-lock.json
> chore: bump website deps and updates packages to document

- packages/network/src/settled-tracking-middleware.ts
see #137
With thanks to @chriskrycho.
> fix: clean up globaThis typing

- package-lock.json
- package.json
- packages/codegen/package.json
- packages/codegen/rollup.config.js
- packages/codegen/tsconfig.json
adds clean before build because it is super foot gunny.
> chore: adds clean before build

- internal-packages/react-graphql-test-app/package.json
- internal-packages/react-graphql-test-app/vite.config.ts
- package-lock.json
> chore: fix demo app to make sure it loads

- package-lock.json
- package.json
- packages/codegen/package.json
- packages/codegen/vitest.config.ts
- packages/mocker/package.json
- packages/mocker/vitest.config.ts
clean was deleting dist folders in nested node_modules which was failing codegen tests.
> chore: fix failing tests by fixing clean functionality

- packages/cache/src/live-transaction.ts
- packages/codegen/__tests__/utils.test.ts
- packages/codegen/__tests__/utils/project.ts
> bug: fixing live-transaction in implementation

- packages/athena/__tests__/client.test.ts
- packages/mocker/README.md
- packages/mocker/__tests__/__snapshots__/mocker.test.ts.snap
- packages/mocker/__tests__/mocker.test.ts
- packages/mocker/src/index.ts
> feat: make mocker.mock synchronous

- packages/mocker/__tests__/mocker.test.ts
- packages/mocker/src/index.ts
allows you to validate fields with fieldGenerators
> feat: field generators should be able to validate mocked content
